runtime: go
api_version: go1
application: thegoapp
version: 1

handlers:  

- url: /
  script: _go_app
- url: /_ah/warmup
  script: _go_app

  - url: /login.*
  script: _go_app 

- url: /ws/.*
  script: _go_app

- url: /callbacks/*
  script: _go_app


- url: /static/img
  static_dir: static/img
- url: /static/css
  static_dir: static/css
- url: /static/js
  static_dir: static/js


inbound_services:
- warmup